tmr_jobeet_job:
    resource: "@TmrJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /api/job/

tmr_jobeet_homepage:
    path:     /
    defaults: { _controller: TmrJobeetBundle:Default:index }
